/** Official Isabela City barangays (45) — `(code, name)` pairs IC-001…IC-045. Keep aligned with `backend/prisma/seed.ts` and mobile `isabela_seed_barangays.dart`. */
const BARANGAY_NAMES = [
  "Aguada",
  "Balatanay",
  "Baluno",
  "Begang",
  "Binuangan",
  "Busay",
  "Cabunbata",
  "Calvario",
  "Carbon",
  "Diki",
  "Isabela Eastside",
  "Isabela Proper",
  "Dona Ramona T. Alano",
  "Kapatagan Grande",
  "Kaumpurnah Zone I",
  "Kaumpurnah Zone II",
  "Kaumpurnah Zone III",
  "Kapayawan",
  "Kumalarang",
  "La Piedad",
  "Lampinigan",
  "Lanote",
  "Lukbuton",
  "Lumbang",
  "Makiri",
  "Maligue",
  "Marang-marang",
  "Marketsite",
  "Masula",
  "Menzi",
  "Panigayan",
  "Panunsulan",
  "Port Area",
  "Riverside",
  "San Rafael",
  "Santa Barbara",
  "Santa Cruz",
  "Seaside",
  "Small Kapatagan",
  "Sumagdang",
  "Sunrise Village",
  "Tabiawan",
  "Tabuk",
  "Tampalan",
  "Timpul",
] as const;

export const IABELA_SEED_BARANGAY_PAIRS: ReadonlyArray<readonly [string, string]> = BARANGAY_NAMES.map(
  (name, i) => [`IC-${String(i + 1).padStart(3, "0")}`, name],
);
