/**
 * Official reference: 45 barangays of Isabela City, Basilan (EOC / coordination).
 * Distinct from DB seed codes — use for display and planning; API remains source of truth for IDs.
 */
export const ISABELA_CITY_OFFICIAL_BARANGAYS: readonly string[] = [
  "Aguada",
  "Balatanay",
  "Baluno",
  "Begang",
  "Binuangan",
  "Busay",
  "Cabunbata",
  "Calvario",
  "Carbon",
  "Diki",
  "Isabela Eastside",
  "Isabela Proper",
  "Dona Ramona T. Alano",
  "Kapatagan Grande",
  "Kaumpurnah Zone I",
  "Kaumpurnah Zone II",
  "Kaumpurnah Zone III",
  "Kapayawan",
  "Kumalarang",
  "La Piedad",
  "Lampinigan",
  "Lanote",
  "Lukbuton",
  "Lumbang",
  "Makiri",
  "Maligue",
  "Marang-marang",
  "Marketsite",
  "Masula",
  "Menzi",
  "Panigayan",
  "Panunsulan",
  "Port Area",
  "Riverside",
  "San Rafael",
  "Santa Barbara",
  "Santa Cruz",
  "Seaside",
  "Small Kapatagan",
  "Sumagdang",
  "Sunrise Village",
  "Tabiawan",
  "Tabuk",
  "Tampalan",
  "Timpul",
] as const;

export const ISABELA_CITY_OFFICIAL_BARANGAY_COUNT = ISABELA_CITY_OFFICIAL_BARANGAYS.length;
