include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-cascade: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: false
